# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af97396aa6573e3e73827e5d84666bde84c69ed7582ec83bdbe5ed4816f45b91936ce4e80825c9d05e2ad6cedfba1b171313ef0f7d8d5c89444922d3051dff41

test:
  secret_key_base: e06fda0f4dad77dcc7412f8dbb244d28e812e200229f5fa2ef174366a3f310146952867cc78e457840d4e2e7b8ad35937e62e4517bff36a901f60e55d179cc13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
